version: '3.7'

services:
  postgres:
    container_name: pg_database
    image: postgres
    restart: unless-stopped
    ports:
      - ${DB_PG_PORT}:5432
    environment:
      POSTGRES_HOST: ${DB_PG_HOST}
      POSTGRES_PORT: ${DB_PG_PORT}
      POSTGRES_DB: ${DB_PG_DB_NAME}
      POSTGRES_USER: ${DB_PG_USER}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./docker/databases/postgres/init:/docker-entrypoint.initdb.d
